// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b504181a-8aa6-466c-9c18-35151e10d9dd";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onEsp32RelayChange();

float dht22_humedad;
float dht22_temperatura;
bool esp32_relay;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(dht22_humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dht22_temperatura, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(esp32_relay, READWRITE, ON_CHANGE, onEsp32RelayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
