#include "arduino_secrets.h"
// DHT sensor library for ESPx - Version: Latest 
#include <DHTesp.h>

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/eda6a3a1-c30a-4b78-8d11-64d978fb2e51 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float dht22_humedad;
  float dht22_temperatura;
  bool esp32_relay;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
DHTesp dht;
#define relay_gpio 16
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  dht.setup(4,DHTesp::DHT22);
  pinMode(relay_gpio, OUTPUT);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  dht22_temperatura = dht.getTemperature();
  dht22_humedad = dht.getHumidity();
  delay(5000);
  
}






/*
  Since Esp32Relay is READ_WRITE variable, onEsp32RelayChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onEsp32RelayChange()  {
  // Add your code here to act upon Esp32Relay change
  if (esp32_relay){
    digitalWrite(relay_gpio, HIGH);
  } else {
    digitalWrite(relay_gpio, LOW);
  }
}